- name: Get SSH key contents
  slurp:
    src: "{{ git_ssh_private_key_path }}"
  register: git_ssh_key_contents

- name: Create K8S secret
  community.kubernetes.k8s:
    apply: yes
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: flux-ssh
        namespace: flux
      data:
        identity: "{{ git_ssh_key_contents.content }}"
  no_log: true
