repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik
    namespace: traefik
    createNamespace: true
    chart: traefik/traefik