- name: Bootstrap cluster
  hosts: master
  vars:
    update_k3s: no # Update k3s to latest version
  environment:
    KUBECONFIG: "{{ playbook_dir }}/kubeconfig.k3s"
  tasks:
    - name: Check if k3s is running
      command: pgrep k3s
      ignore_errors: yes
      register: k3s_running

    - name: Bootstrap cluster
      import_tasks: "{{ playbook_dir }}/roles/bootstrap/tasks/main.yml"
      become: yes
      when: k3s_running.failed or update_k3s

    - name: Install pip3
      become: yes
      apt:
        name: python3-pip
        state: present

- name: Setup Helm installs
  hosts: localhost
  environment:
    KUBECONFIG: "{{ playbook_dir }}/kubeconfig.k3s"
  vars:
    git_repo_url: https://github.com/adace123/k8s-homelab.git
    git_ssh_private_key_path: "~/.ssh/github"
    skip_brew_installs: false
    recreate_tls_cert: false
  tasks:
    - name: Install required Brew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_items:
        - kubectl
        - helm
        - kubectx
        - flux
      when: "not skip_brew_installs"

    - name: Install required pip packages
      pip:
        name: "{{ item }}"
      with_items:
        - PyYaml

    # - name: Cert Manager
    #   include_role:
    #     name: cert-manager

    - name: Install Flux 2
      include_role:
        name: flux2
