apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux
spec:
  wait: true
  releaseName: cert-manager
  targetNamespace: cert-manager
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: 1.3.1
