---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: default
spec:
  wait: true
  releaseName: prometheus
  targetNamespace: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts/
    name: prometheus
    version: 13.3.3
  values:
    kube-state-metrics:
      image:
        repository: carlosedp/kube-state-metrics
        tag: v1.9.6
