apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux
spec:
  wait: true
  releaseName: prometheus
  targetNamespace: prometheus
  chart:
    repository: https://prometheus-community.github.io/helm-charts/
    name: prometheus
    version: 13.3.3
  values:
    kube-state-metrics:
      image:
        repository: carlosedp/kube-state-metrics
        tag: v1.9.6
    server:
      ingress:
        enabled: true
        hosts:
          - prometheus.k8shomelab.duckdns.org/
        tls:
          - secretName: prometheus-server-tls
            hosts:
              - prometheus.k8shomelab.duckdns.org
        annotations:
          cert-manager.io/cluster-issuer: "cert-manager-webhook-duckdns-production"
