apiVersion: v1
kind: Namespace
metadata:
  name: prometheus

---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  url: https://prometheus-community.github.io/helm-charts/

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus
      version: 13.3.3
      sourceRef:
        kind: HelmRepository
        name: prometheus
  values:
    kube-state-metrics:
      image:
        repository: carlosedp/kube-state-metrics
        tag: v1.9.6
    server:
      ingress:
        enabled: true
        hosts:
          - prometheus.k8shomelab.duckdns.org
        tls:
          - secretName: prometheus-server-tls
            hosts:
              - prometheus.k8shomelab.duckdns.org
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          traefik.ingress.kubernetes.io/router.tls: "true"
