apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  url: https://helm.traefik.io/traefik

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 9.18.2
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService

---
kind: Service
apiVersion: v1
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  selector:
    app.kubernetes.io/name: traefik
  ports:
  - name: http
    port: 80
    targetPort: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    traefik.ingress.kubernetes.io/redirect-regex: https://traefik.k8shomelab.duckdns.org
    traefik.ingress.kubernetes.io/redirect-replacement: https://traefik.k8shomelab.duckdns.org/dashboard/
  name: traefik-dashboard
  namespace: traefik
spec:
  rules:
  - host: traefik.k8shomelab.duckdns.org
    http:
      paths:
      - backend:
          service:
            name: traefik-dashboard
            port:
              number: 80
        path: /dashboard
        pathType: ImplementationSpecific
      - backend:
          service:
            name: traefik-dashboard
            port:
              number: 80
        path: /api
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - traefik.k8shomelab.duckdns.org
    secretName: traefik-dashboard-tls
