apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux
spec:
  wait: true
  releaseName: traefik
  targetNamespace: traefik
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.18.2
  values:
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
