apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  url: https://helm.traefik.io/traefik

---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 9.18.2
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-web-ui
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
  - match: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
