apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux
spec:
  wait: true
  releaseName: traefik
  targetNamespace: traefik
  chart:
    repository: https://helm.traefik.io/traefik
    name: traefik
    version: 9.18.2
  values:
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    ingressRoute:
      dashboard:
        enabled: false

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-ingress
  namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
      - traefik.k8shomelab.duckdns.org
    secretName: traefik-dashboard-tls
  rules:
  - host: traefik.k8shomelab.duckdns.org
    http:
      paths:
      - path: /dashboard
        pathType: Prefix
        backend:
          service:
            name: traefik
            port:
              number: 80
