apiVersion: v1
kind: Namespace
metadata:
  name: vault
---

apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: vault
spec:
  interval: 10m
  url: https://helm.releases.hashicorp.com

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 10m
  chart:
    spec:
      chart: vault
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: vault.k8shomelab.duckdns.org
      tls:
        - secretName: vault-tls
          hosts:
            - vault.k8shomelab.duckdns.org
    server:
      dataStorage:
        size: 5Gi
    ui:
      enabled: true
