- name: Install CoreDNS
  community.kubernetes.helm:
    name: coredns
    chart_ref: coredns/coredns
    release_namespace: coredns
    wait: yes
    atomic: yes
    wait_timeout: 5m
    values:
      isClusterService: false
      rbac:
        create: true
      zoneFiles:
        - filename: kubelocal.db
          domain: "{{ k8s_dns_domain }}"
          contents: |
            {{ k8s_dns_domain }}.   IN SOA sns.dns.icann.com. noc.dns.icann.com. 2015082541 7200 3600 1209600 3600
            {{ k8s_dns_domain }}.   IN NS  {{ groups['master'][0] }}
            {{ k8s_dns_domain }}.   IN A   {{ groups['master'][0] }}
            *.{{ k8s_dns_domain }}. IN A   {{ groups['master'][0] }}
      servers:
      - zones:
        - zone: .
        port: 53
        plugins:
          - name: file
            parameters: "/etc/coredns/kubelocal.db {{ k8s_dns_domain }} *.{{ k8s_dns_domain }}"
          - name: errors
          - name: health
            configBlock: |-
              lameduck 5s
          - name: ready
          - name: kubernetes
            parameters: cluster.local in-addr.arpa ip6.arpa
            configBlock: |-
              pods insecure
              fallthrough in-addr.arpa ip6.arpa
              ttl 30
          - name: prometheus
            parameters: 0.0.0.0:9153
          - name: forward
            parameters: . tls://1.1.1.1 tls://1.0.0.1
            configBlock: |
              tls_servername cloudflare-dns.com
              health_check 5s
          - name: cache
            parameters: 30
          - name: loop
          - name: reload
          - name: loadbalance

- name: Expose CoreDNS
  community.kubernetes.k8s_service:
    state: present
    name: coredns-lb
    namespace: coredns
    type: LoadBalancer
    ports:
    - port: 53
      protocol: UDP
    selector:
      app.kubernetes.io/name: coredns
