apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kubelocal-cert
  namespace: cert-manager
spec:
  commonName: "*.kube.local.io"
  secretName: kubelocal-cert
  issuerRef:
    name: cluster-cert-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.kube.local.io"
    - "kube.local.io"
