apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kubelocal-cert
  namespace: cert-manager
spec:
  commonName: "*.{{ k8s_base_domain }}"
  secretName: kubelocal-cert
  issuerRef:
    name: cluster-cert-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.{{ k8s_base_domain }}"
    - "{{ k8s_base_domain }}"
